controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
accueil_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /etudiant
        permanent: true
